### ISSUE TITLE
Precompiled executables

### ISSUE THREAD

**Issue by flippette** [PoshoDev/Twig#1]
Sorry for interrupting but can you please provide precompiled builds? (I don't know how to compile this to binaries)

**Comment by PoshoDev** [comment]
Hey,

I was going to release a build once the program is stable. But as of now, it is pretty messy.

I can compile you an EXE if you'd like, though.

**Comment by flippette** [comment]
I'm running macOS so can you compile to it in 64 bit? Thanks in advance, and if you don't want to do it right now then perhaps I could download the engine and try to compile this (I know literally nothing outside of Unity though)

**Comment by PoshoDev** [comment]
I am afraid that I can't compile this to MacOS as of now. I need to own a Mac device to do so.

**Comment by flippette** [comment]
Ok, so just compile an EXE is fine. I'll run it through WINE

**Comment by PoshoDev** [comment]
Alright, I'll put up an EXE with the latest stable version with a quick README. But you've been warned that despite it being able to save/load data, it's pretty useless as of now.

**Comment by PoshoDev** [comment]
It's up now. You download it [here](https://github.com/PoshoDev/Twig/releases/tag/v0.1.0-prealpha). I'll update the ReadMe file now to help you use it.

**Comment by PoshoDev** [comment]
I just updated the [README](https://github.com/PoshoDev/Twig/blob/master/README.md) file. If you need anything else, please let me know :)

**Comment by flippette** [comment]
Ok, very nice. Thanks!

**Comment by flippette** [comment]
By the way, is this expected?
<img width="811" alt="Screen Shot 2020-02-29 at 08 07 34" src="https://user-images.githubusercontent.com/43138244/75597877-8cc78100-5aca-11ea-9063-f8c1a96b2c9f.png">

**Comment by PoshoDev** [comment]
Nope, not at all. Can you recall what were you doing before it happened?

**Comment by flippette** [comment]
> Nope, not at all. Can you recall what were you doing before it happened?

I middle-moused on the first and only dialog box.

**Comment by PoshoDev** [comment]
Ah okay. It's just the program not knowing what to do when deleting a dialog box with no parent(s). Will have to work on that one later.
